config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"
  get "/firstpage" , to: "pages#first_page"
  get "/login" , to: "pages#login"
  get "/register" , to: "pages#register"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def first_page
 end

 def login
 end

 def register
 	
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Volcanicfrontendtest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/first_page.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbarBG">
  <a class="navbar-brand" href="#"><%= image_tag "logovolcanic.png", style: "height: 4vh; margin-bottom: 7px;" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">JOBS <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">ABOUT</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CANDIDATES</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CLIENTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">JOIN US</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">INSIGHTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">CONTACT US</a>
      </li>
      <%= link_to "LOGIN", login_path, class: "btn btn-primary loginBtn" %>
      <%= link_to "REGISTER", register_path, class: "btn btn-success registerBtn" %>
    </ul>
   
  </div>
</nav>

<div style="height: 59vh; position: static">
	<div>
	<%= image_tag 'mainbanner.jpg', class: "mainBanner" %>
	<h1 style="position: absolute;top: 50%; left: 50%; transform: translate(-50%, -50%); color: #fff; text-align: center;">Accusantium doloremque quae ab illo</h1>
</div>
</div>


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%#image_tag "pic1.jpg", class: "d-block w-100", alt: "First slide" %>
      <div class="d-block w-100" style="height: 20vh; background-color: rgba(24,36,54,0.65);">
      	<div style="display: flex; justify-content: space-evenly; padding-top: 4vh; width: 80%; margin-left: auto; margin-right: auto">
      		<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px;", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
				</div>
			</div>
    </div>
    

    <div class="carousel-item">
      <div class="d-block w-100" style="height: 20vh; background-color: rgba(24,36,54,0.65);">
				<div style="display: flex; justify-content: space-evenly; padding-top: 4vh; width: 80%; margin-left: auto; margin-right: auto">
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
					<div class="contentSlider">
						<div class="borderContent">
							<%= image_tag "pinwheel.png", style: "height: 40px; padding: 5px", alt: "First slide" %>
						</div>
						<p>Eiusmod tempor</p>
					</div>
				</div>
			</div>
    </div>
    
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<section class="latestJobSection">
	<h2 style="text-align: center; margin-bottom: 5vh;">Latest Jobs</h2>
	<div style="display: flex; width: 95%; margin-left: auto; margin-right: auto;">
		<div class="card" style="width: 20rem; font-size: .8em; margin: 1px">
		  <div class="card-body">
		    <h5 class="card-title">Card title</h5>
		    <h6 class="card-subtitle">Card subtitle</h6>
		    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
		  </div>
		    <a href="#" class="card-link">APPLY</a>
		</div>
		<div class="card" style="width: 20rem; font-size: .8em; margin: 1px">
		  <div class="card-body">
		    <h5 class="card-title">Card title</h5>
		    <h6 class="card-subtitle">Card subtitle</h6>
		    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
		  </div>
		    <a href="#" class="card-link">APPLY</a>
		</div>
		<div class="card" style="width: 20rem; font-size: .8em; margin: 1px">
		  <div class="card-body">
		    <h5 class="card-title">Card title</h5>
		    <h6 class="card-subtitle">Card subtitle</h6>
		    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
		  </div>
		    <a href="#" class="card-link">APPLY</a>
		</div>
		<div class="card" style="width: 20rem; font-size: .8em; margin: 1px">
		  <div class="card-body">
		    <h5 class="card-title">Card title</h5>
		    <h6 class="card-subtitle">Card subtitle</h6>
		    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
		  </div>
		    <a href="#" class="card-link">APPLY</a>
		</div>
		<div class="card" style="width: 20rem; font-size: .8em; margin: 1px">
		  <div class="card-body">
		    <h5 class="card-title">Card title</h5>
		    <h6 class="card-subtitle">Card subtitle</h6>
		    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
		  </div>
		    <a href="#" class="card-link">APPLY</a>
		</div>
	</div>
</section>

app/views/pages/home.html.erb
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4">Collapsed content</h5>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  	<a class="navbar-brand mx-auto" href="#"><%= image_tag "logo.png", class: "headerLogo" %></a>
  </nav>
</div>

<div class="container-fluid bigcontainer" >
  <div class="row contentrow">
    <div class="col-md-6 col-12">
      <%= link_to firstpage_path do %>
    	<%= image_tag "pic1.jpg", class: "contentImage" %>
    	<div class="contentContainer">
    		<div class="contentDescription">
	    		<h3 class="contentHeaderBold">WHAT WE DO</h3>
	    		<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	    		<button class="contentReadMore">READ MORE</button>
    		</div>
    	</div>
      <% end %>
    </div>
    <div class="col-md-6 col-12">
    	<%= image_tag "pic2.jpg", class: "contentImage"  %>
    	<div class="contentContainer">
	    	<div class="contentDescription">
		    	<h3 class="contentHeaderBold">OUR METHODOLOGY</h3>
		    	<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		    	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	    		<button class="contentReadMore">READ MORE</button>
	    	</div>
	    </div>
    </div>
  </div>
  <div class="row contentrow">
    <div class="col-md-6 col-sm-12">
    	<%= image_tag "pic3.jpg", class: "contentImage"  %>
    	<div class="contentContainer">
	    	<div class="contentDescription">
		    	<h3 class="contentHeaderBold">WHAT WE'RE LISTENING TO</h3>
		    	<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		    	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	    		<button class="contentReadMore">READ MORE</button>
	    	</div>
	    </div>
    </div>
   <div class="col-md-6 col-sm-12">
    	<%= image_tag "pic4.jpg", class: "contentImage"  %>
    	<div class="contentContainer">
	    	<div class="contentDescription">
		    	<h3 class="contentHeaderBold">CONTACT</h3>
		    	<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	    	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	    		<button class="contentReadMore">READ MORE</button>
	    	</div>
	    </div>
    </div>
  </div>
</div>

app/views/pages/login.html.erb
<h1>LOGIN PAGE</h1>

app/views/pages/register.html.erb
<h1>REGISTER PAGE</h1>